services:
  - type: web
    name: char-hack-api
    env: node
    region: singapore
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18.0.0

  - type: worker
    name: char-hack-bot
    env: node
    region: singapore
    buildCommand: npm install
    startCommand: node bot.js
    plan: free
    envVars:
      - key: TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: API_URL
        sync: false
